(use-modules (guix packages)
             (guix download)
             (guix git-download)
             (guix build-system r)
             (guix licenses))

;; Use version ahead of current cran release to take advantage of
;; <https://github.com/haozhu233/kableExtra/pull/851>. once that is on cran,
;; we can use their version again.
(define-public r-kableextra
  (let ((commit "cc2bd72e62291fd7af19b24e5128c50628d0d9ea")
        (revision "1"))
    (package
      (name "r-kableextra")
      (version (git-version "1.4.0.4" revision commit))
      (source
       (origin
         (method git-fetch)
         (uri (git-reference
               (url "https://github.com/haozhu233/kableExtra")
               (commit commit)))
         (file-name (git-file-name name version))
         (sha256
          (base32 "11jgs3w0hqajniwa7dcg7szrqcd40najz2dmp1r00i131ybv0gzv"))))
      (properties `((upstream-name . "kableExtra")))
      (build-system r-build-system)
      (propagated-inputs (list (specification->package "r-digest")
                               (specification->package "r-htmltools")
                               (specification->package "r-knitr")
                               (specification->package "r-magrittr")
                               (specification->package "r-rmarkdown")
                               (specification->package "r-rstudioapi")
                               (specification->package "r-scales")
                               (specification->package "r-stringr")
                               (specification->package "r-svglite")
                               (specification->package "r-viridislite")
                               (specification->package "r-xml2")))
      (native-inputs (list (specification->package "esbuild")
                           (specification->package "r-knitr")))
      (home-page "https://github.com/haozhu233/kableExtra")
      (synopsis "Construct Complex Table with 'kable' and Pipe Syntax")
      (description
       "Build complex HTML or @code{LaTeX} tables using kable() from knitr and the
piping syntax from magrittr'.  Function kable() is a light weight table
generator coming from knitr'.  This package simplifies the way to manipulate the
HTML or @code{LaTeX} codes generated by kable() and allows users to construct
complex tables and customize styles using a readable syntax.")
      (license expat))))

(packages->manifest
  (append
    (list r-kableextra)
    (map specification->package
      (list "bibtool"
            "texlive"
            "pandoc"
            "r"
            "r-bookdown"
            "r-data-table"
            "r-dt"
            "r-dplyr"
            "r-here"
            "r-import"
            "r-purrr"
            "r-stringr"
            "r-styler"
            "r-rmarkdown"
            "r-tidyr"
            "r-tinytex"
            "r-withr"
            "r-yaml"))))
