(specifications->manifest (list "bibtool"
                                "texlive"
                                "pandoc"
                                "r"
                                "r-data-table"
                                "r-dt"
                                "r-dplyr"
                                "r-here"
                                "r-stringr"
                                "r-rmarkdown"
                                "r-tinytex"
                                "r-yaml"))